python fedtrain.py data=ml-1m net=fedmf net.init.gmf_emb_size=64 task_name=tuning FED.agg_epochs=1000 TRAIN.log_interval=10 EVAL.interval=100 DATALOADER.batch_size=256 FED.local_epochs=2 TRAIN.lr=0.5 TRAIN.weight_decay=5e-4 EXP.project=lfedrec-mf-tuning TRAIN.wandb=True compression=svd FED.compression_kwargs.rank=32
python fedtrain.py data=ml-1m net=fedmf net.init.gmf_emb_size=64 task_name=tuning FED.agg_epochs=1000 TRAIN.log_interval=10 EVAL.interval=100 DATALOADER.batch_size=256 FED.local_epochs=2 TRAIN.lr=0.5 TRAIN.weight_decay=5e-4 EXP.project=lfedrec-mf-tuning TRAIN.wandb=True compression=svd FED.compression_kwargs.rank=16
python fedtrain.py data=ml-1m net=fedmf net.init.gmf_emb_size=64 task_name=tuning FED.agg_epochs=1000 TRAIN.log_interval=10 EVAL.interval=100 DATALOADER.batch_size=256 FED.local_epochs=2 TRAIN.lr=0.5 TRAIN.weight_decay=5e-4 EXP.project=lfedrec-mf-tuning TRAIN.wandb=True compression=svd FED.compression_kwargs.rank=8
python fedtrain.py data=ml-1m net=fedmf net.init.gmf_emb_size=64 task_name=tuning FED.agg_epochs=1000 TRAIN.log_interval=10 EVAL.interval=100 DATALOADER.batch_size=256 FED.local_epochs=2 TRAIN.lr=0.5 TRAIN.weight_decay=5e-4 EXP.project=lfedrec-mf-tuning TRAIN.wandb=True compression=svd FED.compression_kwargs.rank=4
python fedtrain.py data=ml-1m net=fedmf net.init.gmf_emb_size=64 task_name=tuning FED.agg_epochs=1000 TRAIN.log_interval=10 EVAL.interval=100 DATALOADER.batch_size=256 FED.local_epochs=2 TRAIN.lr=0.5 TRAIN.weight_decay=5e-4 EXP.project=lfedrec-mf-tuning TRAIN.wandb=True compression=svd FED.compression_kwargs.rank=2
# python fedtrain.py data=ml-1m net=fedmf net.init.gmf_emb_size=64 task_name=tuning FED.agg_epochs=1000 TRAIN.log_interval=10 EVAL.interval=100 DATALOADER.batch_size=256 FED.local_epochs=2 TRAIN.lr=0.5 TRAIN.weight_decay=5e-4 EXP.project=lfedrec-mf-tuning TRAIN.wandb=True compression=svd FED.compression_kwargs.rank=1

python fedtrain.py data=ml-1m net=fedmf net.init.gmf_emb_size=64 task_name=tuning FED.agg_epochs=1000 TRAIN.log_interval=10 EVAL.interval=100 DATALOADER.batch_size=256 FED.local_epochs=2 TRAIN.lr=0.5 TRAIN.weight_decay=5e-4 EXP.project=lfedrec-mf-tuning TRAIN.wandb=True compression=topk FED.compression_kwargs.ratio=0.03125
python fedtrain.py data=ml-1m net=fedmf net.init.gmf_emb_size=64 task_name=tuning FED.agg_epochs=1000 TRAIN.log_interval=10 EVAL.interval=100 DATALOADER.batch_size=256 FED.local_epochs=2 TRAIN.lr=0.5 TRAIN.weight_decay=5e-4 EXP.project=lfedrec-mf-tuning TRAIN.wandb=True compression=topk FED.compression_kwargs.ratio=0.0625
python fedtrain.py data=ml-1m net=fedmf net.init.gmf_emb_size=64 task_name=tuning FED.agg_epochs=1000 TRAIN.log_interval=10 EVAL.interval=100 DATALOADER.batch_size=256 FED.local_epochs=2 TRAIN.lr=0.5 TRAIN.weight_decay=5e-4 EXP.project=lfedrec-mf-tuning TRAIN.wandb=True compression=topk FED.compression_kwargs.ratio=0.125
python fedtrain.py data=ml-1m net=fedmf net.init.gmf_emb_size=64 task_name=tuning FED.agg_epochs=1000 TRAIN.log_interval=10 EVAL.interval=100 DATALOADER.batch_size=256 FED.local_epochs=2 TRAIN.lr=0.5 TRAIN.weight_decay=5e-4 EXP.project=lfedrec-mf-tuning TRAIN.wandb=True compression=topk FED.compression_kwargs.ratio=0.25
python fedtrain.py data=ml-1m net=fedmf net.init.gmf_emb_size=64 task_name=tuning FED.agg_epochs=1000 TRAIN.log_interval=10 EVAL.interval=100 DATALOADER.batch_size=256 FED.local_epochs=2 TRAIN.lr=0.5 TRAIN.weight_decay=5e-4 EXP.project=lfedrec-mf-tuning TRAIN.wandb=True compression=topk FED.compression_kwargs.ratio=0.5